version: '3'

services:

  frontend:
    container_name: frontend
    deploy:
      replicas: 2
    image: icclabcna/ccp2-k8s-todo-frontend
    ports:
      - '80:8080'
    environment:
      API_ENDPOINT_URL: http://api:8081

  api:
    container_name: api
    deploy:
      replicas: 2
    image: icclabcna/ccp2-k8s-todo-api
    environment:
      REDIS_ENDPOINT: redis
      REDIS_PWD: ccp2

  redis:
    container_name: redis
    image: redis:3.2.10-alpine
    command: "redis-server --requirepass ccp2 --appendonly yes"
    restart: on-failure
    deploy:
      placement:
        constraints:
          - "node.role==manager"
